In [1]:
!pip install IPython

Requirement already satisfied: IPython in c:\python\lib\site-packages (8.27.0)
Requirement already satisfied: decorator in c:\python\lib\site-packages (from IPython) (5.1.1)
Requirement already satisfied: jedi>=0.16 in c:\python\lib\site-packages (from IPython) (0.19.1)
Requirement already satisfied: matplotlib-inline in c:\python\lib\site-packages (from IPython) (0.1.6)
Requirement already satisfied: prompt-toolkit<3.1.0,>=3.0.41 in c:\python\lib\site-packages (from IPython) (3.0.43)
Requirement already satisfied: pygments>=2.4.0 in c:\python\lib\site-packages (from IPython) (2.15.1)
Requirement already satisfied: stack-data in c:\python\lib\site-packages (from IPython) (0.2.0)
Requirement already satisfied: traitlets>=5.13.0 in c:\python\lib\site-packages (from IPython) (5.14.3)
Requirement already satisfied: colorama in c:\python\lib\site-packages (from IPython) (0.4.6)
Requirement already satisfied: parso<0.9.0,>=0.8.3 in c:\python\lib\site-packages (from jedi>=0.16->IPython) (0.8.3)
Requirement already satisfied: wcwidth in c:\python\lib\site-packages (from prompt-toolkit<3.1.0,>=3.0.41->IPython) (0.2.5)
Requirement already satisfied: executing in c:\python\lib\site-packages (from stack-data->IPython) (0.8.3)
Requirement already satisfied: asttokens in c:\python\lib\site-packages (from stack-data->IPython) (2.0.5)
Requirement already satisfied: pure-eval in c:\python\lib\site-packages (from stack-data->IPython) (0.2.2)
Requirement already satisfied: six in c:\python\lib\site-packages (from asttokens->stack-data->IPython) (1.16.0)

In [2]:
!pip install pydotplus

Requirement already satisfied: pydotplus in c:\python\lib\site-packages (2.0.2)
Requirement already satisfied: pyparsing>=2.0.1 in c:\python\lib\site-packages (from pydotplus) (3.1.2)

In [3]:
import yfinance

Stock_ticker = "AMD"
Start_date = "2019-01-01"
End_date = "2024-01-01"

dataframe = yfinance.download(tickers = Stock_ticker,
                 start = Start_date,
                end = End_date)
dataframe

[*********************100%***********************]  1 of 1 completed

Price            Close        High         Low        Open     Volume
Ticker             AMD         AMD         AMD         AMD        AMD
Date
2019-01-02   18.830000   19.000000   17.980000   18.010000   87148700
2019-01-03   17.049999   18.680000   16.940001   18.420000  117277600
2019-01-04   19.000000   19.070000   17.430000   17.549999  111878600
2019-01-07   20.570000   20.680000   19.000000   19.440001  107157000
2019-01-08   20.750000   21.200001   19.680000   21.190001  121271000
...                ...         ...         ...         ...        ...
2023-12-22  139.600006  140.699997  138.309998  140.479996   35370400
2023-12-26  143.410004  143.850006  139.919998  140.070007   47157400
2023-12-27  146.070007  146.250000  143.179993  144.720001   49033400
2023-12-28  148.759995  150.410004  145.949997  146.800003   63800700
2023-12-29  147.410004  151.050003  147.199997  149.500000   62028200

[1258 rows x 5 columns]

In [4]:
import numpy

Buy = 1
Sell = 0

dataframe["Buy or Sell"] = numpy.where(dataframe["Close"].shift(-1) > dataframe["Close"], Buy, Sell)

dataframe

Price,Close,High,Low,Open,Volume,Buy or Sell
Ticker,AMD,AMD,AMD,AMD,AMD,
Date,,,,,,
2019-01-02,18.830000,19.000000,17.980000,18.010000,87148700,0
2019-01-03,17.049999,18.680000,16.940001,18.420000,117277600,1
2019-01-04,19.000000,19.070000,17.430000,17.549999,111878600,1
2019-01-07,20.570000,20.680000,19.000000,19.440001,107157000,1
2019-01-08,20.750000,21.200001,19.680000,21.190001,121271000,0
...,...,...,...,...,...,...
2023-12-22,139.600006,140.699997,138.309998,140.479996,35370400,1
2023-12-26,143.410004,143.850006,139.919998,140.070007,47157400,1
2023-12-27,146.070007,146.250000,143.179993,144.720001,49033400,1
2023-12-28,148.759995,150.410004,145.949997,146.800003,63800700,0
2023-12-29,147.410004,151.050003,147.199997,149.500000,62028200,0

In [5]:
dataframe["Buy or Sell on Open"] = numpy.where(dataframe["Open"].shift(-1) > dataframe["Open"], Buy, Sell)

dataframe

Price,Close,High,Low,Open,Volume,Buy or Sell,Buy or Sell on Open
Ticker,AMD,AMD,AMD,AMD,AMD,,
Date,,,,,,,
2019-01-02,18.830000,19.000000,17.980000,18.010000,87148700,0,1
2019-01-03,17.049999,18.680000,16.940001,18.420000,117277600,1,0
2019-01-04,19.000000,19.070000,17.430000,17.549999,111878600,1,1
2019-01-07,20.570000,20.680000,19.000000,19.440001,107157000,1,1
2019-01-08,20.750000,21.200001,19.680000,21.190001,121271000,0,0
...,...,...,...,...,...,...,...
2023-12-22,139.600006,140.699997,138.309998,140.479996,35370400,1,0
2023-12-26,143.410004,143.850006,139.919998,140.070007,47157400,1,1
2023-12-27,146.070007,146.250000,143.179993,144.720001,49033400,1,1
2023-12-28,148.759995,150.410004,145.949997,146.800003,63800700,0,1
2023-12-29,147.410004,151.050003,147.199997,149.500000,62028200,0,0

In [6]:
dataframe["Returns"] = dataframe["Close"].pct_change()

dataframe

Price,Close,High,Low,Open,Volume,Buy or Sell,Buy or Sell on Open,Returns
Ticker,AMD,AMD,AMD,AMD,AMD,,,
Date,,,,,,,,
2019-01-02,18.830000,19.000000,17.980000,18.010000,87148700,0,1,NaN
2019-01-03,17.049999,18.680000,16.940001,18.420000,117277600,1,0,-0.094530
2019-01-04,19.000000,19.070000,17.430000,17.549999,111878600,1,1,0.114370
2019-01-07,20.570000,20.680000,19.000000,19.440001,107157000,1,1,0.082632
2019-01-08,20.750000,21.200001,19.680000,21.190001,121271000,0,0,0.008751
...,...,...,...,...,...,...,...,...
2023-12-22,139.600006,140.699997,138.309998,140.479996,35370400,1,0,-0.002216
2023-12-26,143.410004,143.850006,139.919998,140.070007,47157400,1,1,0.027292
2023-12-27,146.070007,146.250000,143.179993,144.720001,49033400,1,1,0.018548
2023-12-28,148.759995,150.410004,145.949997,146.800003,63800700,0,1,0.018416
2023-12-29,147.410004,151.050003,147.199997,149.500000,62028200,0,0,-0.009075

In [7]:
dataframe = dataframe.dropna()

dataframe

Price,Close,High,Low,Open,Volume,Buy or Sell,Buy or Sell on Open,Returns
Ticker,AMD,AMD,AMD,AMD,AMD,,,
Date,,,,,,,,
2019-01-03,17.049999,18.680000,16.940001,18.420000,117277600,1,0,-0.094530
2019-01-04,19.000000,19.070000,17.430000,17.549999,111878600,1,1,0.114370
2019-01-07,20.570000,20.680000,19.000000,19.440001,107157000,1,1,0.082632
2019-01-08,20.750000,21.200001,19.680000,21.190001,121271000,0,0,0.008751
2019-01-09,20.190001,21.440001,20.070000,20.889999,163944100,0,0,-0.026988
...,...,...,...,...,...,...,...,...
2023-12-22,139.600006,140.699997,138.309998,140.479996,35370400,1,0,-0.002216
2023-12-26,143.410004,143.850006,139.919998,140.070007,47157400,1,1,0.027292
2023-12-27,146.070007,146.250000,143.179993,144.720001,49033400,1,1,0.018548
2023-12-28,148.759995,150.410004,145.949997,146.800003,63800700,0,1,0.018416
2023-12-29,147.410004,151.050003,147.199997,149.500000,62028200,0,0,-0.009075

In [8]:
Volume_Drop = 1
Volume_Increase = 0

dataframe["Volume Increase or Decrease"] = numpy.where(dataframe["Volume"].shift(-1) > dataframe["Volume"], Volume_Drop, Volume_Increase)

dataframe

C:\Users\David Moon\AppData\Local\Temp\ipykernel_20104\3675090710.py:4: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  dataframe["Volume Increase or Decrease"] = numpy.where(dataframe["Volume"].shift(-1) > dataframe["Volume"], Volume_Drop, Volume_Increase)

Price,Close,High,Low,Open,Volume,Buy or Sell,Buy or Sell on Open,Returns,Volume Increase or Decrease
Ticker,AMD,AMD,AMD,AMD,AMD,,,,
Date,,,,,,,,,
2019-01-03,17.049999,18.680000,16.940001,18.420000,117277600,1,0,-0.094530,0
2019-01-04,19.000000,19.070000,17.430000,17.549999,111878600,1,1,0.114370,0
2019-01-07,20.570000,20.680000,19.000000,19.440001,107157000,1,1,0.082632,1
2019-01-08,20.750000,21.200001,19.680000,21.190001,121271000,0,0,0.008751,1
2019-01-09,20.190001,21.440001,20.070000,20.889999,163944100,0,0,-0.026988,0
...,...,...,...,...,...,...,...,...,...
2023-12-22,139.600006,140.699997,138.309998,140.479996,35370400,1,0,-0.002216,1
2023-12-26,143.410004,143.850006,139.919998,140.070007,47157400,1,1,0.027292,1
2023-12-27,146.070007,146.250000,143.179993,144.720001,49033400,1,1,0.018548,1
2023-12-28,148.759995,150.410004,145.949997,146.800003,63800700,0,1,0.018416,0
2023-12-29,147.410004,151.050003,147.199997,149.500000,62028200,0,0,-0.009075,0

In [9]:
X = dataframe.drop(["Buy or Sell"], axis = 1)

X

Price,Close,High,Low,Open,Volume,Buy or Sell on Open,Returns,Volume Increase or Decrease
Ticker,AMD,AMD,AMD,AMD,AMD,,,
Date,,,,,,,,
2019-01-03,17.049999,18.680000,16.940001,18.420000,117277600,0,-0.094530,0
2019-01-04,19.000000,19.070000,17.430000,17.549999,111878600,1,0.114370,0
2019-01-07,20.570000,20.680000,19.000000,19.440001,107157000,1,0.082632,1
2019-01-08,20.750000,21.200001,19.680000,21.190001,121271000,0,0.008751,1
2019-01-09,20.190001,21.440001,20.070000,20.889999,163944100,0,-0.026988,0
...,...,...,...,...,...,...,...,...
2023-12-22,139.600006,140.699997,138.309998,140.479996,35370400,0,-0.002216,1
2023-12-26,143.410004,143.850006,139.919998,140.070007,47157400,1,0.027292,1
2023-12-27,146.070007,146.250000,143.179993,144.720001,49033400,1,0.018548,1
2023-12-28,148.759995,150.410004,145.949997,146.800003,63800700,1,0.018416,0
2023-12-29,147.410004,151.050003,147.199997,149.500000,62028200,0,-0.009075,0

In [10]:
y = dataframe["Buy or Sell"]

y

Date
2019-01-03    1
2019-01-04    1
2019-01-07    1
2019-01-08    0
2019-01-09    0
             ..
2023-12-22    1
2023-12-26    1
2023-12-27    1
2023-12-28    0
2023-12-29    0
Name: Buy or Sell, Length: 1257, dtype: int32

In [11]:
X.info()

<class 'pandas.core.frame.DataFrame'>
DatetimeIndex: 1257 entries, 2019-01-03 to 2023-12-29
Data columns (total 8 columns):
 #   Column                           Non-Null Count  Dtype
---  ------                           --------------  -----
 0   (Close, AMD)                     1257 non-null   float64
 1   (High, AMD)                      1257 non-null   float64
 2   (Low, AMD)                       1257 non-null   float64
 3   (Open, AMD)                      1257 non-null   float64
 4   (Volume, AMD)                    1257 non-null   int64
 5   (Buy or Sell on Open, )          1257 non-null   int32
 6   (Returns, )                      1257 non-null   float64
 7   (Volume Increase or Decrease, )  1257 non-null   int32
dtypes: float64(5), int32(2), int64(1)
memory usage: 78.6 KB

In [12]:
y.info()

<class 'pandas.core.series.Series'>
DatetimeIndex: 1257 entries, 2019-01-03 to 2023-12-29
Series name: Buy or Sell
Non-Null Count  Dtype
--------------  -----
1257 non-null   int32
dtypes: int32(1)
memory usage: 14.7 KB

In [13]:
from sklearn.tree import DecisionTreeClassifier

model = DecisionTreeClassifier(random_state = 0)

model = model.fit(X, y)

from sklearn import tree

visualization_data = tree.export_graphviz(model, out_file = None, feature_names = X.columns, class_names = ["Buy", "Sell"])

visualization_data

'digraph Tree {\nnode [shape=box, fontname="helvetica"] ;\nedge [fontname="helvetica"] ;\n0 [label="(\'Buy or Sell on Open\', \'\') <= 0.5\\ngini = 0.5\\nsamples = 1257\\nvalue = [619, 638]\\nclass = Sell"] ;\n1 [label="(\'Returns\', \'\') <= -0.019\\ngini = 0.495\\nsamples = 598\\nvalue = [330, 268]\\nclass = Buy"] ;\n0 -> 1 [labeldistance=2.5, labelangle=45, headlabel="True"] ;\n2 [label="(\'Close\', \'AMD\') <= 29.765\\ngini = 0.498\\nsamples = 250\\nvalue = [117, 133]\\nclass = Sell"] ;\n1 -> 2 ;\n3 [label="(\'Volume\', \'AMD\') <= 99493752.0\\ngini = 0.346\\nsamples = 27\\nvalue = [6, 21]\\nclass = Sell"] ;\n2 -> 3 ;\n4 [label="(\'Volume\', \'AMD\') <= 61564350.0\\ngini = 0.18\\nsamples = 20\\nvalue = [2, 18]\\nclass = Sell"] ;\n3 -> 4 ;\n5 [label="(\'Open\', \'AMD\') <= 26.225\\ngini = 0.444\\nsamples = 6\\nvalue = [2, 4]\\nclass = Sell"] ;\n4 -> 5 ;\n6 [label="(\'Open\', \'AMD\') <= 23.42\\ngini = 0.444\\nsamples = 3\\nvalue = [2, 1]\\nclass = Buy"] ;\n5 -> 6 ;\n7 [label="gini = 0.0\\nsamples = 1\\nvalue = [0, 1]\\nclass = Sell"] ;\n6 -> 7 ;\n8 [label="gini = 0.0\\nsamples = 2\\nvalue = [2, 0]\\nclass = Buy"] ;\n6 -> 8 ;\n9 [label="gini = 0.0\\nsamples = 3\\nvalue = [0, 3]\\nclass = Sell"] ;\n5 -> 9 ;\n10 [label="gini = 0.0\\nsamples = 14\\nvalue = [0, 14]\\nclass = Sell"] ;\n4 -> 10 ;\n11 [label="(\'High\', \'AMD\') <= 20.42\\ngini = 0.49\\nsamples = 7\\nvalue = [4, 3]\\nclass = Buy"] ;\n3 -> 11 ;\n12 [label="gini = 0.0\\nsamples = 2\\nvalue = [0, 2]\\nclass = Sell"] ;\n11 -> 12 ;\n13 [label="(\'High\', \'AMD\') <= 28.45\\ngini = 0.32\\nsamples = 5\\nvalue = [4, 1]\\nclass = Buy"] ;\n11 -> 13 ;\n14 [label="gini = 0.0\\nsamples = 3\\nvalue = [3, 0]\\nclass = Buy"] ;\n13 -> 14 ;\n15 [label="(\'High\', \'AMD\') <= 29.235\\ngini = 0.5\\nsamples = 2\\nvalue = [1, 1]\\nclass = Buy"] ;\n13 -> 15 ;\n16 [label="gini = 0.0\\nsamples = 1\\nvalue = [0, 1]\\nclass = Sell"] ;\n15 -> 16 ;\n17 [label="gini = 0.0\\nsamples = 1\\nvalue = [1, 0]\\nclass = Buy"] ;\n15 -> 17 ;\n18 [label="(\'Close\', \'AMD\') <= 32.73\\ngini = 0.5\\nsamples = 223\\nvalue = [111, 112]\\nclass = Sell"] ;\n2 -> 18 ;\n19 [label="gini = 0.0\\nsamples = 8\\nvalue = [8, 0]\\nclass = Buy"] ;\n18 -> 19 ;\n20 [label="(\'Low\', \'AMD\') <= 51.665\\ngini = 0.499\\nsamples = 215\\nvalue = [103, 112]\\nclass = Sell"] ;\n18 -> 20 ;\n21 [label="(\'Volume\', \'AMD\') <= 79966348.0\\ngini = 0.346\\nsamples = 18\\nvalue = [4, 14]\\nclass = Sell"] ;\n20 -> 21 ;\n22 [label="gini = 0.0\\nsamples = 9\\nvalue = [0, 9]\\nclass = Sell"] ;\n21 -> 22 ;\n23 [label="(\'Volume\', \'AMD\') <= 90391252.0\\ngini = 0.494\\nsamples = 9\\nvalue = [4, 5]\\nclass = Sell"] ;\n21 -> 23 ;\n24 [label="gini = 0.0\\nsamples = 4\\nvalue = [4, 0]\\nclass = Buy"] ;\n23 -> 24 ;\n25 [label="gini = 0.0\\nsamples = 5\\nvalue = [0, 5]\\nclass = Sell"] ;\n23 -> 25 ;\n26 [label="(\'High\', \'AMD\') <= 56.63\\ngini = 0.5\\nsamples = 197\\nvalue = [99.0, 98.0]\\nclass = Buy"] ;\n20 -> 26 ;\n27 [label="gini = 0.0\\nsamples = 5\\nvalue = [5, 0]\\nclass = Buy"] ;\n26 -> 27 ;\n28 [label="(\'High\', \'AMD\') <= 147.31\\ngini = 0.5\\nsamples = 192\\nvalue = [94, 98]\\nclass = Sell"] ;\n26 -> 28 ;\n29 [label="(\'High\', \'AMD\') <= 138.42\\ngini = 0.499\\nsamples = 185\\nvalue = [88, 97]\\nclass = Sell"] ;\n28 -> 29 ;\n30 [label="(\'Close\', \'AMD\') <= 125.15\\ngini = 0.5\\nsamples = 179\\nvalue = [88, 91]\\nclass = Sell"] ;\n29 -> 30 ;\n31 [label="(\'Returns\', \'\') <= -0.019\\ngini = 0.499\\nsamples = 175\\nvalue = [84, 91]\\nclass = Sell"] ;\n30 -> 31 ;\n32 [label="(\'Returns\', \'\') <= -0.036\\ngini = 0.5\\nsamples = 171\\nvalue = [84, 87]\\nclass = Sell"] ;\n31 -> 32 ;\n33 [label="(\'High\', \'AMD\') <= 82.275\\ngini = 0.483\\nsamples = 76\\nvalue = [31, 45]\\nclass = Sell"] ;\n32 -> 33 ;\n34 [label="(\'Volume\', \'AMD\') <= 99198096.0\\ngini = 0.365\\nsamples = 25\\nvalue = [6, 19]\\nclass = Sell"] ;\n33 -> 34 ;\n35 [label="(\'Close\', \'AMD\') <= 71.36\\ngini = 0.236\\nsamples = 22\\nvalue = [3, 19]\\nclass = Sell"] ;\n34 -> 35 ;\n36 [label="(\'Close\', \'AMD\') <= 68.32\\ngini = 0.444\\nsamples = 9\\nvalue = [3, 6]\\nclass = Sell"] ;\n35 -> 36 ;\n37 [label="(\'Returns\', \'\') <= -0.063\\ngini = 0.245\\nsamples = 7\\nvalue = [1, 6]\\nclass = Sell"] ;\n36 -> 37 ;\n38 [label="(\'Open\', \'AMD\') <= 56.325\\ngini = 0.5\\nsamples = 2\\nvalue = [1, 1]\\nclass = Buy"] ;\n37 -> 38 ;\n39 [label="gini = 0.0\\nsamples = 1\\nvalue = [0, 1]\\nclass = Sell"] ;\n38 -> 39 ;\n40 [label="gini = 0.0\\nsamples = 1\\nvalue = [1, 0]\\nclass = Buy"] ;\n38 -> 40 ;\n41 [label="gini = 0.0\\nsamples = 5\\nvalue = [0, 5]\\nclass = Sell"] ;\n37 -> 41 ;\n42 [label="gini = 0.0\\nsamples = 2\\nvalue = [2, 0]\\nclass = Buy"] ;\n36 -> 42 ;\n43 [label="gini = 0.0\\nsamples = 13\\nvalue = [0, 13]\\nclass = Sell"] ;\n35 -> 43 ;\n44 [label="gini = 0.0\\nsamples = 3\\nvalue = [3, 0]\\nclass = Buy"] ;\n34 -> 44 ;\n45 [label="(\'Low\', \'AMD\') <= 80.935\\ngini = 0.5\\nsamples = 51\\nvalue = [25, 26]\\nclass = Sell"] ;\n33 -> 45 ;\n46 [label="gini = 0.0\\nsamples = 5\\nvalue = [5, 0]\\nclass = Buy"] ;\n45 -> 46 ;\n47 [label="(\'Volume\', \'AMD\') <= 105868252.0\\ngini = 0.491\\nsamples = 46\\nvalue = [20.0, 26.0]\\nclass = Sell"] ;\n45 -> 47 ;\n48 [label="(\'Returns\', \'\') <= -0.057\\ngini = 0.495\\nsamples = 31\\nvalue = [17, 14]\\nclass = Buy"] ;\n47 -> 48 ;\n49 [label="gini = 0.0\\nsamples = 7\\nvalue = [7, 0]\\nclass = Buy"] ;\n48 -> 49 ;\n50 [label="(\'Open\', \'AMD\') <= 88.1\\ngini = 0.486\\nsamples = 24\\nvalue = [10, 14]\\nclass = Sell"] ;\n48 -> 50 ;\n51 [label="gini = 0.0\\nsamples = 5\\nvalue = [0, 5]\\nclass = Sell"] ;\n50 -> 51 ;\n52 [label="(\'Close\', \'AMD\') <= 96.085\\ngini = 0.499\\nsamples = 19\\nvalue = [10, 9]\\nclass = Buy"] ;\n50 -> 52 ;\n53 [label="(\'Volume Increase or Decrease\', \'\') <= 0.5\\ngini = 0.219\\nsamples = 8\\nvalue = [7, 1]\\nclass = Buy"] ;\n52 -> 53 ;\n54 [label="gini = 0.0\\nsamples = 6\\nvalue = [6, 0]\\nclass = Buy"] ;\n53 -> 54 ;\n55 [label="(\'Close\', \'AMD\') <= 89.215\\ngini = 0.5\\nsamples = 2\\nvalue = [1, 1]\\nclass = Buy"] ;\n53 -> 55 ;\n56 [label="gini = 0.0\\nsamples = 1\\nvalue = [1, 0]\\nclass = Buy"] ;\n55 -> 56 ;\n57 [label="gini = 0.0\\nsamples = 1\\nvalue = [0, 1]\\nclass = Sell"] ;\n55 -> 57 ;\n58 [label="(\'Returns\', \'\') <= -0.042\\ngini = 0.397\\nsamples = 11\\nvalue = [3, 8]\\nclass = Sell"] ;\n52 -> 58 ;\n59 [label="(\'Close\', \'AMD\') <= 120.05\\ngini = 0.219\\nsamples = 8\\nvalue = [1, 7]\\nclass = Sell"] ;\n58 -> 59 ;\n60 [label="gini = 0.0\\nsamples = 7\\nvalue = [0, 7]\\nclass = Sell"] ;\n59 -> 60 ;\n61 [label="gini = 0.0\\nsamples = 1\\nvalue = [1, 0]\\nclass = Buy"] ;\n59 -> 61 ;\n62 [label="(\'High\', \'AMD\') <= 108.57\\ngini = 0.444\\nsamples = 3\\nvalue = [2, 1]\\nclass = Buy"] ;\n58 -> 62 ;\n63 [label="gini = 0.0\\nsamples = 1\\nvalue = [0, 1]\\nclass = Sell"] ;\n62 -> 63 ;\n64 [label="gini = 0.0\\nsamples = 2\\nvalue = [2, 0]\\nclass = Buy"] ;\n62 -> 64 ;\n65 [label="(\'Low\', \'AMD\') <= 108.2\\ngini = 0.32\\nsamples = 15\\nvalue = [3, 12]\\nclass = Sell"] ;\n47 -> 65 ;\n66 [label="gini = 0.0\\nsamples = 8\\nvalue = [0, 8]\\nclass = Sell"] ;\n65 -> 66 ;\n67 [label="(\'High\', \'AMD\') <= 118.455\\ngini = 0.49\\nsamples = 7\\nvalue = [3, 4]\\nclass = Sell"] ;\n65 -> 67 ;\n68 [label="gini = 0.0\\nsamples = 3\\nvalue = [3, 0]\\nclass = Buy"] ;\n67 -> 68 ;\n69 [label="gini = 0.0\\nsamples = 4\\nvalue = [0, 4]\\nclass = Sell"] ;\n67 -> 69 ;\n70 [label="(\'Volume\', \'AMD\') <= 61329950.0\\ngini = 0.493\\nsamples = 95\\nvalue = [53.0, 42.0]\\nclass = Buy"] ;\n32 -> 70 ;\n71 [label="(\'Returns\', \'\') <= -0.034\\ngini = 0.492\\nsamples = 55\\nvalue = [24.0, 31.0]\\nclass = Sell"] ;\n70 -> 71 ;\n72 [label="gini = 0.0\\nsamples = 4\\nvalue = [4, 0]\\nclass = Buy"] ;\n71 -> 72 ;\n73 [label="(\'Volume\', \'AMD\') <= 47971800.0\\ngini = 0.477\\nsamples = 51\\nvalue = [20.0, 31.0]\\nclass = Sell"] ;\n71 -> 73 ;\n74 [label="(\'Open\', \'AMD\') <= 80.475\\ngini = 0.493\\nsamples = 25\\nvalue = [14.0, 11.0]\\nclass = Buy"] ;\n73 -> 74 ;\n75 [label="(\'Open\', \'AMD\') <= 75.48\\ngini = 0.245\\nsamples = 7\\nvalue = [6, 1]\\nclass = Buy"] ;\n74 -> 75 ;\n76 [label="(\'Close\', \'AMD\') <= 68.23\\ngini = 0.5\\nsamples = 2\\nvalue = [1, 1]\\nclass = Buy"] ;\n75 -> 76 ;\n77 [label="gini = 0.0\\nsamples = 1\\nvalue = [1, 0]\\nclass = Buy"] ;\n76 -> 77 ;\n78 [label="gini = 0.0\\nsamples = 1\\nvalue = [0, 1]\\nclass = Sell"] ;\n76 -> 78 ;\n79 [label="gini = 0.0\\nsamples = 5\\nvalue = [5, 0]\\nclass = Buy"] ;\n75 -> 79 ;\n80 [label="(\'Low\', \'AMD\') <= 83.49\\ngini = 0.494\\nsamples = 18\\nvalue = [8, 10]\\nclass = Sell"] ;\n74 -> 80 ;\n81 [label="(\'Volume\', \'AMD\') <= 45509500.0\\ngini = 0.245\\nsamples = 7\\nvalue = [1, 6]\\nclass = Sell"] ;\n80 -> 81 ;\n82 [label="gini = 0.0\\nsamples = 6\\nvalue = [0, 6]\\nclass = Sell"] ;\n81 -> 82 ;\n83 [label="gini = 0.0\\nsamples = 1\\nvalue = [1, 0]\\nclass = Buy"] ;\n81 -> 83 ;\n84 [label="(\'Returns\', \'\') <= -0.022\\ngini = 0.463\\nsamples = 11\\nvalue = [7, 4]\\nclass = Buy"] ;\n80 -> 84 ;\n85 [label="(\'Volume\', \'AMD\') <= 47214500.0\\ngini = 0.219\\nsamples = 8\\nvalue = [7, 1]\\nclass = Buy"] ;\n84 -> 85 ;\n86 [label="gini = 0.0\\nsamples = 7\\nvalue = [7, 0]\\nclass = Buy"] ;\n85 -> 86 ;\n87 [label="gini = 0.0\\nsamples = 1\\nvalue = [0, 1]\\nclass = Sell"] ;\n85 -> 87 ;\n88 [label="gini = 0.0\\nsamples = 3\\nvalue = [0, 3]\\nclass = Sell"] ;\n84 -> 88 ;\n89 [label="(\'High\', \'AMD\') <= 112.755\\ngini = 0.355\\nsamples = 26\\nvalue = [6, 20]\\nclass = Sell"] ;\n73 -> 89 ;\n90 [label="(\'Low\', \'AMD\') <= 88.95\\ngini = 0.278\\nsamples = 24\\nvalue = [4, 20]\\nclass = Sell"] ;\n89 -> 90 ;\n91 [label="(\'High\', \'AMD\') <= 92.935\\ngini = 0.391\\nsamples = 15\\nvalue = [4, 11]\\nclass = Sell"] ;\n90 -> 91 ;\n92 [label="(\'Volume\', \'AMD\') <= 57658250.0\\ngini = 0.337\\nsamples = 14\\nvalue = [3, 11]\\nclass = Sell"] ;\n91 -> 92 ;\n93 [label="(\'Returns\', \'\') <= -0.02\\ngini = 0.18\\nsamples = 10\\nvalue = [1, 9]\\nclass = Sell"] ;\n92 -> 93 ;\n94 [label="gini = 0.0\\nsamples = 8\\nvalue = [0, 8]\\nclass = Sell"] ;\n93 -> 94 ;\n95 [label="(\'Volume\', \'AMD\') <= 51927250.0\\ngini = 0.5\\nsamples = 2\\nvalue = [1, 1]\\nclass = Buy"] ;\n93 -> 95 ;\n96 [label="gini = 0.0\\nsamples = 1\\nvalue = [1, 0]\\nclass = Buy"] ;\n95 -> 96 ;\n97 [label="gini = 0.0\\nsamples = 1\\nvalue = [0, 1]\\nclass = Sell"] ;\n95 -> 97 ;\n98 [label="(\'Low\', \'AMD\') <= 62.015\\ngini = 0.5\\nsamples = 4\\nvalue = [2, 2]\\nclass = Buy"] ;\n92 -> 98 ;\n99 [label="gini = 0.0\\nsamples = 1\\nvalue = [1, 0]\\nclass = Buy"] ;\n98 -> 99 ;\n100 [label="(\'Open\', \'AMD\') <= 78.995\\ngini = 0.444\\nsamples = 3\\nvalue = [1, 2]\\nclass = Sell"] ;\n98 -> 100 ;\n101 [label="gini = 0.0\\nsamples = 2\\nvalue = [0, 2]\\nclass = Sell"] ;\n100 -> 101 ;\n102 [label="gini = 0.0\\nsamples = 1\\nvalue = [1, 0]\\nclass = Buy"] ;\n100 -> 102 ;\n103 [label="gini = 0.0\\nsamples = 1\\nvalue = [1, 0]\\nclass = Buy"] ;\n91 -> 103 ;\n104 [label="gini = 0.0\\nsamples = 9\\nvalue = [0, 9]\\nclass = Sell"] ;\n90 -> 104 ;\n105 [label="gini = 0.0\\nsamples = 2\\nvalue = [2, 0]\\nclass = Buy"] ;\n89 -> 105 ;\n106 [label="(\'Open\', \'AMD\') <= 98.125\\ngini = 0.399\\nsamples = 40\\nvalue = [29, 11]\\nclass = Buy"] ;\n70 -> 106 ;\n107 [label="(\'Volume\', \'AMD\') <= 68426352.0\\ngini = 0.208\\nsamples = 17\\nvalue = [15, 2]\\nclass = Buy"] ;\n106 -> 107 ;\n108 [label="gini = 0.0\\nsamples = 7\\nvalue = [7, 0]\\nclass = Buy"] ;\n107 -> 108 ;\n109 [label="(\'Volume\', \'AMD\') <= 69858248.0\\ngini = 0.32\\nsamples = 10\\nvalue = [8, 2]\\nclass = Buy"] ;\n107 -> 109 ;\n110 [label="gini = 0.0\\nsamples = 1\\nvalue = [0, 1]\\nclass = Sell"] ;\n109 -> 110 ;\n111 [label="(\'Close\', \'AMD\') <= 76.435\\ngini = 0.198\\nsamples = 9\\nvalue = [8, 1]\\nclass = Buy"] ;\n109 -> 111 ;\n112 [label="(\'Close\', \'AMD\') <= 72.18\\ngini = 0.444\\nsamples = 3\\nvalue = [2, 1]\\nclass = Buy"] ;\n111 -> 112 ;\n113 [label="gini = 0.0\\nsamples = 2\\nvalue = [2, 0]\\nclass = Buy"] ;\n112 -> 113 ;\n114 [label="gini = 0.0\\nsamples = 1\\nvalue = [0, 1]\\nclass = Sell"] ;\n112 -> 114 ;\n115 [label="gini = 0.0\\nsamples = 6\\nvalue = [6, 0]\\nclass = Buy"] ;\n111 -> 115 ;\n116 [label="(\'Low\', \'AMD\') <= 96.735\\ngini = 0.476\\nsamples = 23\\nvalue = [14, 9]\\nclass = Buy"] ;\n106 -> 116 ;\n117 [label="gini = 0.0\\nsamples = 3\\nvalue = [0, 3]\\nclass = Sell"] ;\n116 -> 117 ;\n118 [label="(\'Volume\', \'AMD\') <= 76428700.0\\ngini = 0.42\\nsamples = 20\\nvalue = [14, 6]\\nclass = Buy"] ;\n116 -> 118 ;\n119 [label="(\'High\', \'AMD\') <= 103.405\\ngini = 0.375\\nsamples = 4\\nvalue = [1, 3]\\nclass = Sell"] ;\n118 -> 119 ;\n120 [label="gini = 0.0\\nsamples = 1\\nvalue = [1, 0]\\nclass = Buy"] ;\n119 -> 120 ;\n121 [label="gini = 0.0\\nsamples = 3\\nvalue = [0, 3]\\nclass = Sell"] ;\n119 -> 121 ;\n122 [label="(\'High\', \'AMD\') <= 105.795\\ngini = 0.305\\nsamples = 16\\nvalue = [13, 3]\\nclass = Buy"] ;\n118 -> 122 ;\n123 [label="(\'High\', \'AMD\') <= 104.59\\ngini = 0.48\\nsamples = 5\\nvalue = [3, 2]\\nclass = Buy"] ;\n122 -> 123 ;\n124 [label="gini = 0.0\\nsamples = 3\\nvalue = [3, 0]\\nclass = Buy"] ;\n123 -> 124 ;\n125 [label="gini = 0.0\\nsamples = 2\\nvalue = [0, 2]\\nclass = Sell"] ;\n123 -> 125 ;\n126 [label="(\'Volume\', \'AMD\') <= 101905548.0\\ngini = 0.165\\nsamples = 11\\nvalue = [10, 1]\\nclass = Buy"] ;\n122 -> 126 ;\n127 [label="gini = 0.0\\nsamples = 7\\nvalue = [7, 0]\\nclass = Buy"] ;\n126 -> 127 ;\n128 [label="(\'Volume Increase or Decrease\', \'\') <= 0.5\\ngini = 0.375\\nsamples = 4\\nvalue = [3, 1]\\nclass = Buy"] ;\n126 -> 128 ;\n129 [label="gini = 0.0\\nsamples = 3\\nvalue = [3, 0]\\nclass = Buy"] ;\n128 -> 129 ;\n130 [label="gini = 0.0\\nsamples = 1\\nvalue = [0, 1]\\nclass = Sell"] ;\n128 -> 130 ;\n131 [label="gini = 0.0\\nsamples = 4\\nvalue = [0, 4]\\nclass = Sell"] ;\n31 -> 131 ;\n132 [label="gini = 0.0\\nsamples = 4\\nvalue = [4, 0]\\nclass = Buy"] ;\n30 -> 132 ;\n133 [label="gini = 0.0\\nsamples = 6\\nvalue = [0, 6]\\nclass = Sell"] ;\n29 -> 133 ;\n134 [label="(\'Returns\', \'\') <= -0.056\\ngini = 0.245\\nsamples = 7\\nvalue = [6, 1]\\nclass = Buy"] ;\n28 -> 134 ;\n135 [label="gini = 0.0\\nsamples = 1\\nvalue = [0, 1]\\nclass = Sell"] ;\n134 -> 135 ;\n136 [label="gini = 0.0\\nsamples = 6\\nvalue = [6, 0]\\nclass = Buy"] ;\n134 -> 136 ;\n137 [label="(\'Volume\', \'AMD\') <= 53306150.0\\ngini = 0.475\\nsamples = 348\\nvalue = [213.0, 135.0]\\nclass = Buy"] ;\n1 -> 137 ;\n138 [label="(\'Returns\', \'\') <= 0.007\\ngini = 0.499\\nsamples = 178\\nvalue = [93.0, 85.0]\\nclass = Buy"] ;\n137 -> 138 ;\n139 [label="(\'High\', \'AMD\') <= 82.49\\ngini = 0.5\\nsamples = 154\\nvalue = [75, 79]\\nclass = Sell"] ;\n138 -> 139 ;\n140 [label="(\'Open\', \'AMD\') <= 34.075\\ngini = 0.467\\nsamples = 70\\nvalue = [26, 44]\\nclass = Sell"] ;\n139 -> 140 ;\n141 [label="(\'Volume\', \'AMD\') <= 48115850.0\\ngini = 0.469\\nsamples = 24\\nvalue = [15, 9]\\nclass = Buy"] ;\n140 -> 141 ;\n142 [label="(\'Volume\', \'AMD\') <= 29236850.0\\ngini = 0.388\\nsamples = 19\\nvalue = [14, 5]\\nclass = Buy"] ;\n141 -> 142 ;\n143 [label="gini = 0.0\\nsamples = 1\\nvalue = [0, 1]\\nclass = Sell"] ;\n142 -> 143 ;\n144 [label="(\'Volume\', \'AMD\') <= 41324750.0\\ngini = 0.346\\nsamples = 18\\nvalue = [14, 4]\\nclass = Buy"] ;\n142 -> 144 ;\n145 [label="gini = 0.0\\nsamples = 8\\nvalue = [8, 0]\\nclass = Buy"] ;\n144 -> 145 ;\n146 [label="(\'Returns\', \'\') <= -0.007\\ngini = 0.48\\nsamples = 10\\nvalue = [6, 4]\\nclass = Buy"] ;\n144 -> 146 ;\n147 [label="(\'Volume\', \'AMD\') <= 45822600.0\\ngini = 0.375\\nsamples = 4\\nvalue = [1, 3]\\nclass = Sell"] ;\n146 -> 147 ;\n148 [label="gini = 0.0\\nsamples = 3\\nvalue = [0, 3]\\nclass = Sell"] ;\n147 -> 148 ;\n149 [label="gini = 0.0\\nsamples = 1\\nvalue = [1, 0]\\nclass = Buy"] ;\n147 -> 149 ;\n150 [label="(\'Volume\', \'AMD\') <= 41601850.0\\ngini = 0.278\\nsamples = 6\\nvalue = [5, 1]\\nclass = Buy"] ;\n146 -> 150 ;\n151 [label="gini = 0.0\\nsamples = 1\\nvalue = [0, 1]\\nclass = Sell"] ;\n150 -> 151 ;\n152 [label="gini = 0.0\\nsamples = 5\\nvalue = [5, 0]\\nclass = Buy"] ;\n150 -> 152 ;\n153 [label="(\'High\', \'AMD\') <= 23.27\\ngini = 0.32\\nsamples = 5\\nvalue = [1, 4]\\nclass = Sell"] ;\n141 -> 153 ;\n154 [label="gini = 0.0\\nsamples = 1\\nvalue = [1, 0]\\nclass = Buy"] ;\n153 -> 154 ;\n155 [label="gini = 0.0\\nsamples = 4\\nvalue = [0, 4]\\nclass = Sell"] ;\n153 -> 155 ;\n156 [label="(\'Returns\', \'\') <= -0.013\\ngini = 0.364\\nsamples = 46\\nvalue = [11, 35]\\nclass = Sell"] ;\n140 -> 156 ;\n157 [label="(\'Open\', \'AMD\') <= 51.43\\ngini = 0.48\\nsamples = 10\\nvalue = [6, 4]\\nclass = Buy"] ;\n156 -> 157 ;\n158 [label="gini = 0.0\\nsamples = 4\\nvalue = [0, 4]\\nclass = Sell"] ;\n157 -> 158 ;\n159 [label="gini = 0.0\\nsamples = 6\\nvalue = [6, 0]\\nclass = Buy"] ;\n157 -> 159 ;\n160 [label="(\'Low\', \'AMD\') <= 50.87\\ngini = 0.239\\nsamples = 36\\nvalue = [5, 31]\\nclass = Sell"] ;\n156 -> 160 ;\n161 [label="(\'High\', \'AMD\') <= 39.9\\ngini = 0.469\\nsamples = 8\\nvalue = [3, 5]\\nclass = Sell"] ;\n160 -> 161 ;\n162 [label="gini = 0.0\\nsamples = 3\\nvalue = [0, 3]\\nclass = Sell"] ;\n161 -> 162 ;\n163 [label="(\'Returns\', \'\') <= -0.01\\ngini = 0.48\\nsamples = 5\\nvalue = [3, 2]\\nclass = Buy"] ;\n161 -> 163 ;\n164 [label="gini = 0.0\\nsamples = 2\\nvalue = [0, 2]\\nclass = Sell"] ;\n163 -> 164 ;\n165 [label="gini = 0.0\\nsamples = 3\\nvalue = [3, 0]\\nclass = Buy"] ;\n163 -> 165 ;\n166 [label="(\'Returns\', \'\') <= -0.004\\ngini = 0.133\\nsamples = 28\\nvalue = [2, 26]\\nclass = Sell"] ;\n160 -> 166 ;\n167 [label="gini = 0.0\\nsamples = 15\\nvalue = [0, 15]\\nclass = Sell"] ;\n166 -> 167 ;\n168 [label="(\'Returns\', \'\') <= -0.003\\ngini = 0.26\\nsamples = 13\\nvalue = [2, 11]\\nclass = Sell"] ;\n166 -> 168 ;\n169 [label="gini = 0.0\\nsamples = 1\\nvalue = [1, 0]\\nclass = Buy"] ;\n168 -> 169 ;\n170 [label="(\'Volume Increase or Decrease\', \'\') <= 0.5\\ngini = 0.153\\nsamples = 12\\nvalue = [1, 11]\\nclass = Sell"] ;\n168 -> 170 ;\n171 [label="(\'Returns\', \'\') <= 0.003\\ngini = 0.444\\nsamples = 3\\nvalue = [1, 2]\\nclass = Sell"] ;\n170 -> 171 ;\n172 [label="gini = 0.0\\nsamples = 1\\nvalue = [1, 0]\\nclass = Buy"] ;\n171 -> 172 ;\n173 [label="gini = 0.0\\nsamples = 2\\nvalue = [0, 2]\\nclass = Sell"] ;\n171 -> 173 ;\n174 [label="gini = 0.0\\nsamples = 9\\nvalue = [0, 9]\\nclass = Sell"] ;\n170 -> 174 ;\n175 [label="(\'Close\', \'AMD\') <= 105.46\\ngini = 0.486\\nsamples = 84\\nvalue = [49, 35]\\nclass = Buy"] ;\n139 -> 175 ;\n176 [label="(\'Returns\', \'\') <= 0.005\\ngini = 0.437\\nsamples = 59\\nvalue = [40, 19]\\nclass = Buy"] ;\n175 -> 176 ;\n177 [label="(\'Volume\', \'AMD\') <= 52052600.0\\ngini = 0.419\\nsamples = 57\\nvalue = [40, 17]\\nclass = Buy"] ;\n176 -> 177 ;\n178 [label="(\'Volume\', \'AMD\') <= 38127750.0\\ngini = 0.389\\nsamples = 53\\nvalue = [39, 14]\\nclass = Buy"] ;\n177 -> 178 ;\n179 [label="(\'Close\', \'AMD\') <= 92.715\\ngini = 0.473\\nsamples = 26\\nvalue = [16, 10]\\nclass = Buy"] ;\n178 -> 179 ;\n180 [label="(\'Volume\', \'AMD\') <= 33972850.0\\ngini = 0.5\\nsamples = 20\\nvalue = [10, 10]\\nclass = Buy"] ;\n179 -> 180 ;\n181 [label="(\'Volume Increase or Decrease\', \'\') <= 0.5\\ngini = 0.459\\nsamples = 14\\nvalue = [9, 5]\\nclass = Buy"] ;\n180 -> 181 ;\n182 [label="(\'Volume\', \'AMD\') <= 32030550.0\\ngini = 0.375\\nsamples = 4\\nvalue = [1, 3]\\nclass = Sell"] ;\n181 -> 182 ;\n183 [label="gini = 0.0\\nsamples = 3\\nvalue = [0, 3]\\nclass = Sell"] ;\n182 -> 183 ;\n184 [label="gini = 0.0\\nsamples = 1\\nvalue = [1, 0]\\nclass = Buy"] ;\n182 -> 184 ;\n185 [label="(\'Close\', \'AMD\') <= 82.65\\ngini = 0.32\\nsamples = 10\\nvalue = [8, 2]\\nclass = Buy"] ;\n181 -> 185 ;\n186 [label="(\'High\', \'AMD\') <= 82.995\\ngini = 0.5\\nsamples = 4\\nvalue = [2, 2]\\nclass = Buy"] ;\n185 -> 186 ;\n187 [label="gini = 0.0\\nsamples = 2\\nvalue = [2, 0]\\nclass = Buy"] ;\n186 -> 187 ;\n188 [lab

In [14]:
import pydotplus

decision_tree_graph = pydotplus.graph_from_dot_data(visualization_data)

decision_tree_graph

In [20]:
from IPython.display import Image

Image(decision_tree_graph.create_png())

InvocationException: GraphViz's executables not found