In [1]:
import yfinance

Stock_Symbol = "AMD"
Start_Date = "2020-01-01"
End_Date = "2025-01-01"

dataframe = yfinance.download(tickers = Stock_Symbol,
                             start = Start_Date,
                             end = End_Date)

dataframe

[*********************100%***********************]  1 of 1 completed

Price            Close        High         Low        Open    Volume
Ticker             AMD         AMD         AMD         AMD       AMD
Date
2020-01-02   49.099998   49.250000   46.630001   46.860001  80331100
2020-01-03   48.599998   49.389999   47.540001   48.029999  73127400
2020-01-06   48.389999   48.860001   47.860001   48.020000  47934900
2020-01-07   48.250000   49.389999   48.040001   49.349998  58061400
2020-01-08   47.830002   48.299999   47.139999   47.849998  53767000
...                ...         ...         ...         ...       ...
2024-12-24  126.290001  127.510002  124.660004  127.510002  24829600
2024-12-26  125.059998  127.300003  125.050003  125.519997  24998200
2024-12-27  125.190002  126.180000  122.260002  124.370003  32924000
2024-12-30  122.440002  124.099998  122.349998  123.559998  30501600
2024-12-31  120.790001  123.550003  120.139999  123.099998  30203400

[1258 rows x 5 columns]

In [2]:
dataframe["Returns"] = dataframe["Close"].pct_change()

dataframe

Price            Close        High         Low        Open    Volume   Returns
Ticker             AMD         AMD         AMD         AMD       AMD
Date
2020-01-02   49.099998   49.250000   46.630001   46.860001  80331100       NaN
2020-01-03   48.599998   49.389999   47.540001   48.029999  73127400 -0.010183
2020-01-06   48.389999   48.860001   47.860001   48.020000  47934900 -0.004321
2020-01-07   48.250000   49.389999   48.040001   49.349998  58061400 -0.002893
2020-01-08   47.830002   48.299999   47.139999   47.849998  53767000 -0.008705
...                ...         ...         ...         ...       ...       ...
2024-12-24  126.290001  127.510002  124.660004  127.510002  24829600  0.013563
2024-12-26  125.059998  127.300003  125.050003  125.519997  24998200 -0.009740
2024-12-27  125.190002  126.180000  122.260002  124.370003  32924000  0.001040
2024-12-30  122.440002  124.099998  122.349998  123.559998  30501600 -0.021967
2024-12-31  120.790001  123.550003  120.139999  123.099998  30203400 -0.013476

[1258 rows x 6 columns]

In [3]:
dataframe = dataframe.dropna()

In [4]:
dataframe

Price            Close        High         Low        Open    Volume   Returns
Ticker             AMD         AMD         AMD         AMD       AMD
Date
2020-01-03   48.599998   49.389999   47.540001   48.029999  73127400 -0.010183
2020-01-06   48.389999   48.860001   47.860001   48.020000  47934900 -0.004321
2020-01-07   48.250000   49.389999   48.040001   49.349998  58061400 -0.002893
2020-01-08   47.830002   48.299999   47.139999   47.849998  53767000 -0.008705
2020-01-09   48.970001   49.959999   48.389999   48.939999  76512800  0.023834
...                ...         ...         ...         ...       ...       ...
2024-12-24  126.290001  127.510002  124.660004  127.510002  24829600  0.013563
2024-12-26  125.059998  127.300003  125.050003  125.519997  24998200 -0.009740
2024-12-27  125.190002  126.180000  122.260002  124.370003  32924000  0.001040
2024-12-30  122.440002  124.099998  122.349998  123.559998  30501600 -0.021967
2024-12-31  120.790001  123.550003  120.139999  123.099998  30203400 -0.013476

[1257 rows x 6 columns]

In [6]:
import numpy as np

Buy = 1
Sell = 0

dataframe["Buy/Sell on Open"] = np.where(dataframe["Open"].shift(-1) > dataframe["Open"],
                                       Buy,
                                       Sell)
dataframe

C:\Users\David Moon\AppData\Local\Temp\ipykernel_108336\357502640.py:6: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  dataframe["Buy/Sell on Open"] = np.where(dataframe["Open"].shift(-1) > dataframe["Open"],

Price,Close,High,Low,Open,Volume,Returns,Buy/Sell on Open
Ticker,AMD,AMD,AMD,AMD,AMD,,
Date,,,,,,,
2020-01-03,48.599998,49.389999,47.540001,48.029999,73127400,-0.010183,0
2020-01-06,48.389999,48.860001,47.860001,48.020000,47934900,-0.004321,1
2020-01-07,48.250000,49.389999,48.040001,49.349998,58061400,-0.002893,0
2020-01-08,47.830002,48.299999,47.139999,47.849998,53767000,-0.008705,1
2020-01-09,48.970001,49.959999,48.389999,48.939999,76512800,0.023834,1
...,...,...,...,...,...,...,...
2024-12-24,126.290001,127.510002,124.660004,127.510002,24829600,0.013563,0
2024-12-26,125.059998,127.300003,125.050003,125.519997,24998200,-0.009740,0
2024-12-27,125.190002,126.180000,122.260002,124.370003,32924000,0.001040,0
2024-12-30,122.440002,124.099998,122.349998,123.559998,30501600,-0.021967,0
2024-12-31,120.790001,123.550003,120.139999,123.099998,30203400,-0.013476,0

In [8]:
dataframe["Buy/Sell on Close"] = np.where(dataframe["Close"].shift(-1) > dataframe["Close"],
                                       Buy,
                                       Sell)
dataframe

C:\Users\David Moon\AppData\Local\Temp\ipykernel_108336\133397674.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  dataframe["Buy/Sell on Close"] = np.where(dataframe["Close"].shift(-1) > dataframe["Close"],

Price,Close,High,Low,Open,Volume,Returns,Buy/Sell on Open,Buy/Sell on Close
Ticker,AMD,AMD,AMD,AMD,AMD,,,
Date,,,,,,,,
2020-01-03,48.599998,49.389999,47.540001,48.029999,73127400,-0.010183,0,0
2020-01-06,48.389999,48.860001,47.860001,48.020000,47934900,-0.004321,1,0
2020-01-07,48.250000,49.389999,48.040001,49.349998,58061400,-0.002893,0,0
2020-01-08,47.830002,48.299999,47.139999,47.849998,53767000,-0.008705,1,1
2020-01-09,48.970001,49.959999,48.389999,48.939999,76512800,0.023834,1,0
...,...,...,...,...,...,...,...,...
2024-12-24,126.290001,127.510002,124.660004,127.510002,24829600,0.013563,0,0
2024-12-26,125.059998,127.300003,125.050003,125.519997,24998200,-0.009740,0,1
2024-12-27,125.190002,126.180000,122.260002,124.370003,32924000,0.001040,0,0
2024-12-30,122.440002,124.099998,122.349998,123.559998,30501600,-0.021967,0,0
2024-12-31,120.790001,123.550003,120.139999,123.099998,30203400,-0.013476,0,0

In [9]:
Decreased = 1
Increased = 0

dataframe["Volume Increase/Decrease"] = np.where(dataframe["Volume"].shift(-1) > dataframe["Volume"],
                                                Decreased,
                                                Increased)
dataframe

C:\Users\David Moon\AppData\Local\Temp\ipykernel_108336\3964527213.py:4: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  dataframe["Volume Increase/Decrease"] = np.where(dataframe["Volume"].shift(-1) > dataframe["Volume"],

Price,Close,High,Low,Open,Volume,Returns,Buy/Sell on Open,Buy/Sell on Close,Volume Increase/Decrease
Ticker,AMD,AMD,AMD,AMD,AMD,,,,
Date,,,,,,,,,
2020-01-03,48.599998,49.389999,47.540001,48.029999,73127400,-0.010183,0,0,0
2020-01-06,48.389999,48.860001,47.860001,48.020000,47934900,-0.004321,1,0,1
2020-01-07,48.250000,49.389999,48.040001,49.349998,58061400,-0.002893,0,0,0
2020-01-08,47.830002,48.299999,47.139999,47.849998,53767000,-0.008705,1,1,1
2020-01-09,48.970001,49.959999,48.389999,48.939999,76512800,0.023834,1,0,0
...,...,...,...,...,...,...,...,...,...
2024-12-24,126.290001,127.510002,124.660004,127.510002,24829600,0.013563,0,0,1
2024-12-26,125.059998,127.300003,125.050003,125.519997,24998200,-0.009740,0,1,1
2024-12-27,125.190002,126.180000,122.260002,124.370003,32924000,0.001040,0,0,0
2024-12-30,122.440002,124.099998,122.349998,123.559998,30501600,-0.021967,0,0,0
2024-12-31,120.790001,123.550003,120.139999,123.099998,30203400,-0.013476,0,0,0

In [10]:
y = dataframe["Buy/Sell on Close"]

X = dataframe.drop(["Buy/Sell on Close"], axis = 1)

y

Date
2020-01-03    0
2020-01-06    0
2020-01-07    0
2020-01-08    1
2020-01-09    0
             ..
2024-12-24    0
2024-12-26    1
2024-12-27    0
2024-12-30    0
2024-12-31    0
Name: Buy/Sell on Close, Length: 1257, dtype: int32

In [11]:
X

Price,Close,High,Low,Open,Volume,Returns,Buy/Sell on Open,Volume Increase/Decrease
Ticker,AMD,AMD,AMD,AMD,AMD,,,
Date,,,,,,,,
2020-01-03,48.599998,49.389999,47.540001,48.029999,73127400,-0.010183,0,0
2020-01-06,48.389999,48.860001,47.860001,48.020000,47934900,-0.004321,1,1
2020-01-07,48.250000,49.389999,48.040001,49.349998,58061400,-0.002893,0,0
2020-01-08,47.830002,48.299999,47.139999,47.849998,53767000,-0.008705,1,1
2020-01-09,48.970001,49.959999,48.389999,48.939999,76512800,0.023834,1,0
...,...,...,...,...,...,...,...,...
2024-12-24,126.290001,127.510002,124.660004,127.510002,24829600,0.013563,0,1
2024-12-26,125.059998,127.300003,125.050003,125.519997,24998200,-0.009740,0,1
2024-12-27,125.190002,126.180000,122.260002,124.370003,32924000,0.001040,0,0
2024-12-30,122.440002,124.099998,122.349998,123.559998,30501600,-0.021967,0,0
2024-12-31,120.790001,123.550003,120.139999,123.099998,30203400,-0.013476,0,0

In [12]:
from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(X, y)

X_train

Price,Close,High,Low,Open,Volume,Returns,Buy/Sell on Open,Volume Increase/Decrease
Ticker,AMD,AMD,AMD,AMD,AMD,,,
Date,,,,,,,,
2024-11-25,141.130005,142.350006,139.050003,140.490005,30923100,0.020094,1,1
2022-05-11,87.919998,93.459999,86.529999,87.839996,136137900,-0.009129,0,0
2023-05-22,108.000000,108.790001,103.489998,104.680000,65424200,0.020601,1,1
2023-12-22,139.600006,140.699997,138.309998,140.479996,35370400,-0.002216,0,1
2020-12-15,97.120003,97.980003,95.449997,95.930000,57232700,0.024689,1,0
...,...,...,...,...,...,...,...,...
2020-10-06,84.480003,87.250000,83.540001,86.209999,52725400,-0.019385,0,0
2021-03-17,82.629997,83.250000,80.410004,81.750000,43320600,-0.001450,0,1
2022-08-01,96.779999,98.389999,93.959999,95.589996,96477500,0.024452,1,1
2020-08-07,84.849998,87.290001,82.669998,86.669998,66543200,-0.021451,0,1
2021-08-20,104.650002,105.980003,103.989998,104.320000,55227600,0.009161,1,1

In [13]:
from sklearn.preprocessing import StandardScaler

scaler = StandardScaler()

scaler

StandardScaler()

In [14]:
scaler.fit(X_train)

StandardScaler()

In [15]:
X_train = scaler.transform(X_train)

X_train

array([[ 1.0463047 ,  1.00054698,  1.06638939, ...,  0.54686784,
         0.96864421,  1.05456513],
       [-0.44436295, -0.34076433, -0.4313759 , ..., -0.33008125,
        -1.0323708 , -0.94825817],
       [ 0.11817427,  0.07981865,  0.05228929, ...,  0.56208448,
         0.96864421,  1.05456513],
       ...,
       [-0.19615181, -0.20550837, -0.21948718, ...,  0.67765401,
         0.96864421,  1.05456513],
       [-0.53036837, -0.51004   , -0.54145538, ..., -0.69985097,
        -1.0323708 ,  1.05456513],
       [ 0.02432474,  0.00272556,  0.06654829, ...,  0.21878294,
         0.96864421,  1.05456513]])

In [16]:
X_test = scaler.transform(X_test)

X_test

array([[ 0.23331511,  0.36514566,  0.28556651, ..., -1.77699043,
        -1.0323708 , -0.94825817],
       [-1.37809614, -1.38906658, -1.35222192, ...,  0.15979941,
        -1.0323708 ,  1.05456513],
       [-0.49759111, -0.49824282, -0.46930489, ..., -0.17081732,
        -1.0323708 , -0.94825817],
       ...,
       [-0.02330055, -0.00385906, -0.14476995, ...,  1.48216304,
         0.96864421, -0.94825817],
       [-0.57239057, -0.6060635 , -0.5480144 , ...,  0.36370262,
        -1.0323708 , -0.94825817],
       [-0.49394905, -0.53774969, -0.5448774 , ...,  1.53970216,
         0.96864421,  1.05456513]])

In [17]:
y_train

Date
2024-11-25    0
2022-05-11    0
2023-05-22    1
2023-12-22    1
2020-12-15    0
             ..
2020-10-06    1
2021-03-17    0
2022-08-01    1
2020-08-07    0
2021-08-20    1
Name: Buy/Sell on Close, Length: 942, dtype: int32

In [19]:
from sklearn.neural_network import MLPClassifier

Side_Length = 12
Maximum_Epochs = 300

neural_network = MLPClassifier(hidden_layer_sizes = (Side_Length, Side_Length, Side_Length), max_iter = Maximum_Epochs)

neural_network.fit(X_train, y_train)

C:\Python\Lib\site-packages\sklearn\neural_network\_multilayer_perceptron.py:690: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (300) reached and the optimization hasn't converged yet.
  warnings.warn(

MLPClassifier(hidden_layer_sizes=(12, 12, 12), max_iter=300)

In [20]:
predictions = neural_network.predict(X_test)

predictions

array([1, 1, 0, 1, 1, 0, 0, 1, 1, 1, 0, 1, 1, 1, 1, 0, 0, 0, 0, 1, 1, 0,
       0, 0, 1, 1, 1, 0, 0, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 1, 0, 1, 1, 1,
       1, 0, 0, 1, 1, 1, 0, 0, 1, 1, 0, 1, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0,
       0, 0, 0, 1, 1, 0, 0, 0, 0, 1, 0, 0, 1, 1, 0, 1, 1, 0, 0, 0, 0, 0,
       1, 0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 0, 0, 1, 0, 1, 0, 1, 0, 1, 1, 1,
       1, 1, 1, 0, 1, 0, 1, 0, 1, 1, 1, 1, 1, 1, 1, 0, 0, 0, 0, 0, 1, 0,
       0, 1, 0, 1, 1, 1, 1, 1, 1, 0, 1, 0, 1, 0, 1, 1, 1, 1, 0, 0, 0, 0,
       1, 0, 0, 0, 0, 1, 1, 1, 1, 0, 0, 0, 0, 1, 1, 1, 0, 1, 1, 0, 0, 0,
       0, 0, 1, 1, 0, 0, 1, 0, 0, 1, 0, 1, 0, 1, 1, 1, 1, 0, 1, 1, 0, 0,
       1, 0, 0, 1, 0, 0, 0, 0, 1, 1, 1, 0, 0, 1, 0, 1, 1, 1, 1, 0, 1, 0,
       1, 0, 1, 0, 1, 0, 1, 1, 1, 0, 1, 0, 0, 1, 0, 1, 1, 0, 0, 0, 1, 0,
       0, 0, 1, 1, 0, 0, 1, 0, 1, 1, 1, 0, 1, 0, 0, 0, 0, 1, 0, 1, 0, 0,
       1, 1, 0, 0, 1, 1, 1, 1, 0, 0, 0, 0, 1, 0, 1, 0, 1, 1, 1, 0, 1, 0,
       1, 1, 0, 1, 0, 1, 0, 0, 1, 1, 1, 1, 0, 0, 1, 1, 0, 0, 0, 0, 1, 0,
       0, 1, 1, 0, 0, 0, 0])

In [21]:
from sklearn.metrics import confusion_matrix

confusion_matrix(y_test, predictions)

array([[93, 73],
       [67, 82]], dtype=int64)

In [23]:
from sklearn.metrics import classification_report

print(classification_report(y_test, predictions))

              precision    recall  f1-score   support

           0       0.58      0.56      0.57       166
           1       0.53      0.55      0.54       149

    accuracy                           0.56       315
   macro avg       0.56      0.56      0.56       315
weighted avg       0.56      0.56      0.56       315

In [33]:
neural_network.coefs_

[array([[-0.37547131, -0.4450053 ,  0.56213882, -0.57517515,  0.18760941,
          0.63798436, -0.13776801,  0.41086077,  0.09221907, -0.55673024,
         -0.20816149, -0.05600149],
        [-0.42212322,  0.5735774 ,  0.32705352, -0.5348596 , -0.736027  ,
          0.01994211,  0.18129048, -0.36109276,  0.15458111, -0.38120078,
          0.25580243,  0.0225527 ],
        [ 0.18976304, -0.23078364,  0.40845788, -0.61167898, -0.37748023,
          0.46162914,  0.27578221, -0.036787  , -0.15958665,  0.04798705,
         -0.22162979,  0.47354094],
        [-0.43689759,  0.4006624 , -0.39396953, -0.15588933, -0.14924743,
          0.03173771, -0.40131777, -0.0895062 ,  0.0622693 ,  0.39959997,
         -0.37742674,  0.17752126],
        [-0.35611109, -0.04925833,  0.70347152, -0.03845588,  0.5098466 ,
         -0.35025356, -0.19850274, -0.29427324, -0.40890881,  0.02125328,
          0.75799905,  0.59035235],
        [-0.56522666, -0.48330261,  0.23663637, -0.10169262,  0.36541262,
         -0.04650253,  0.03399813,  0.63185505, -0.6017892 ,  0.30713137,
          0.45972204, -0.27222375],
        [-0.09039726, -0.68738093, -0.21098546,  0.20267653, -0.62146364,
          0.50694832, -0.52746193, -0.16092433,  0.34134284,  0.69371706,
          0.06293891,  0.72022392],
        [ 0.48553123, -0.06811445,  0.57035577,  0.24458182, -0.65833472,
          0.56913798, -0.36241879, -0.50329773,  0.5417988 , -0.05699729,
         -0.02153571, -0.46949797]]),
 array([[-0.34677058, -0.61293622, -0.66914214, -0.22963178, -0.19717551,
         -0.4040748 , -0.0837514 ,  0.36752608,  0.43446634, -0.33339358,
          0.23580239, -0.43498366],
        [-0.74905258,  0.8123135 , -0.31788948, -0.19423881, -0.26410756,
         -0.2395145 , -0.528597  , -0.03822712, -0.11995335,  0.13062034,
         -0.17036239,  0.26169293],
        [ 0.1449262 ,  0.22834956,  0.43494119,  0.78328168,  0.31837063,
          0.146087  ,  0.06570799, -0.68018348,  0.22197465,  0.05492339,
          0.54653904,  0.24348655],
        [-0.6797645 ,  0.18969332, -0.27239072,  0.16621964,  0.08623772,
         -0.21899512,  0.46126044,  0.49959438, -0.09267096,  0.24099938,
          0.02303935,  0.21703958],
        [ 0.03746945, -0.08937488,  0.4651725 , -0.206999  ,  0.45641814,
         -0.49534656, -0.19272874, -0.24407273,  0.04945454, -0.0948776 ,
          0.53648739,  0.19558179],
        [-0.78228599,  0.38025133,  0.43174644, -0.20264835,  0.61888782,
          0.01266358, -0.57559622,  0.19456117,  0.04021945, -0.06777512,
          0.10384142,  0.09547945],
        [ 0.39726577, -0.07481969,  0.19448284,  0.39284504, -0.59433843,
         -0.68613903, -0.36022832,  0.02261595,  0.22839876, -0.00889843,
          0.63293385, -0.3471074 ],
        [-0.40917279, -0.06583664, -0.32934457,  0.22591798, -0.35345845,
         -0.28887382,  0.123158  ,  0.39133657, -0.51226131,  0.82364085,
         -0.00251429,  0.06164142],
        [ 0.75353038, -0.59157738, -0.52454533, -0.72941972,  0.01657599,
         -0.18949811,  0.04702597, -0.26999009,  0.30044691,  0.08372755,
         -0.25345667, -0.76566472],
        [-0.49549441, -0.28370801,  0.40587305, -0.41278854,  0.39243292,
          0.49571204,  0.19879724,  0.10282714,  0.57894073, -0.0297649 ,
         -0.14504625, -0.0374721 ],
        [ 0.3412916 , -0.15037376, -0.01110159,  0.04031319, -0.0566013 ,
          0.43179182, -0.27599271,  0.5037596 ,  0.17289041,  0.63179049,
          0.19096485,  0.397509  ],
        [ 0.26305766,  0.24234533, -0.19591004,  0.36829546,  0.32408834,
         -0.18535679,  0.06506894, -0.59931064,  0.43022748, -0.72104667,
          0.21797728,  0.30798791]]),
 array([[ 1.13194588e+00,  1.60806133e-15,  1.18519464e-01,
          3.26055726e-01, -8.87896601e-03,  6.17785566e-01,
         -2.08266313e-01, -1.95998896e-01, -9.22236371e-01,
          1.82657285e-01, -7.48843935e-01, -9.23106638e-01],
        [-5.04243313e-01, -5.25109350e-01, -3.01114680e-01,
          2.58673544e-01,  6.89001272e-01, -3.52172812e-01,
          2.96218787e-01,  4.60420351e-01, -7.18872796e-01,
          1.61683541e-01,  1.17924974e-01, -3.88355834e-01],
        [ 1.54468539e-01, -7.96947642e-01, -2.55030766e-01,
          5.55439739e-01, -1.64035905e-01,  4.95093441e-01,
         -8.64081381e-02,  5.46866645e-02,  2.58831939e-01,
          3.34489832e-01, -4.14731552e-02, -2.42736613e-01],
        [ 5.82736783e-01, -6.50453799e-01, -7.58979368e-01,
         -2.83041071e-01, -4.22302471e-01, -5.38753325e-01,
          1.49514101e-01, -3.52848782e-01, -2.10574793e-01,
          2.51472639e-01, -6.49103753e-01, -2.87768269e-01],
        [ 6.52698666e-02, -7.31993772e-01,  3.04222390e-01,
          6.75157994e-02, -3.69599652e-01, -4.73407141e-01,
         -3.95708675e-01,  3.09124350e-01, -3.39963156e-01,
         -9.96667416e-01,  4.40828686e-01,  1.41932769e-01],
        [-8.76989288e-01,  2.35199388e-01,  2.49194718e-01,
         -6.32518174e-01,  3.18887292e-01, -5.46356492e-01,
          9.82115292e-02, -8.76880457e-01,  8.23991470e-01,
          1.96806668e-01,  4.60551427e-01,  4.34542818e-01],
        [-6.88286392e-01,  1.61524460e-01,  5.25181562e-01,
          3.50619645e-02, -4.17705722e-01, -2.91787491e-01,
          4.96174663e-01,  3.34879696e-01,  1.00784491e-01,
          1.03525742e-23, -2.01897902e-03,  5.33715966e-01],
        [-7.54211849e-02,  3.56594836e-01, -3.27914337e-01,
          4.75512225e-03,  5.34253306e-01,  5.78237426e-01,
         -1.32108764e+00,  3.91451306e-01,  1.20197868e-01,
         -9.04258815e-01,  4.41156639e-01, -1.63687945e-02],
        [-1.18059185e-01,  1.30846970e-02,  2.10069919e-01,
         -5.98806797e-01, -2.66536044e-01, -4.42520491e-01,
         -1.17015178e-01,  2.86432259e-01, -4.09186631e-01,
         -2.14028685e-01, -2.72274180e-01,  5.64191911e-01],
        [-2.94980885e-01,  2.78031128e-01, -5.79192782e-01,
          2.96856701e-01, -1.52806003e-01,  1.71684462e-02,
         -7.87250898e-01, -4.27523880e-02,  3.95278839e-01,
         -3.62729402e-01,  5.29148358e-01, -2.88459081e-02],
        [-7.21676161e-02,  1.14990309e-01,  5.76702349e-01,
          1.82426789e-01, -4.64955209e-01, -3.32473916e-01,
          5.20431486e-02, -5.18972280e-01,  4.40274397e-01,
         -7.82065219e-02,  4.85064122e-01,  3.92042167e-01],
        [ 4.69670568e-01, -3.59905062e-01, -4.88779433e-01,
          2.63165471e-02,  1.96931847e-01,  6.40835465e-01,
          4.06480552e-01,  3.34441284e-01, -8.89089423e-02,
         -3.93130372e-01, -3.28853207e-01,  4.10824664e-01]]),
 array([[-0.54952364],
        [-0.73508019],
        [ 1.16777917],
        [-0.77104476],
        [-0.38602986],
        [-1.09119092],
        [ 1.15214383],
        [-0.20119346],
        [ 0.55189566],
        [ 1.23027025],
        [ 0.16287915],
        [ 0.72846137]])]

In [34]:
neural_network.intercepts_

[array([-0.28874495, -0.2686836 ,  0.17124975,  0.4992655 ,  0.10943685,
         0.65297901, -0.13876812,  0.05844834, -0.05266537,  0.47188913,
         0.27885386,  0.04549476]),
 array([ 0.29761037,  0.05660085, -0.03161364,  0.51010009, -0.34962641,
        -0.19632878, -0.275653  ,  0.30038594, -0.2540622 , -0.16806232,
         0.35739574,  0.06234141]),
 array([ 0.39141404, -0.18460807,  0.44261418,  0.41562306,  0.28991877,
         0.19219797,  0.08139689, -0.19458793, -0.03894679,  0.25598742,
        -0.23320684, -0.00607207]),
 array([-0.12683605])]